name: Security Checks

on:
  schedule:
    - cron: "0 0 * * 0" # every Sunday at midnight UTC

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Composer audit
        run: composer audit || echo "Composer audit found vulnerabilities"

      - name: Cache pnpm packages
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
        with:
          version: 8.6.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: pnpm audit
        run: pnpm audit --audit-level=moderate || echo "pnpm audit found vulnerabilities"
